export const LIST_SERVICETYPES = 'FETCH_SERVICETYPES';
export const UPDATE_SERVICETYPES = 'UPDATE_SERVICETYPES';
export const GET_SERVICETYPE = 'GET_SERVICETYPE';
export const LIST_SUBCATEGORIES = 'LIST_SUBCATEGORIES';
export const UPDATE_SUBCATEGORY = 'UPDATE_SUBCATEGORY';
export const GET_SUBCATEGORY = 'GET_SUBCATEGORY';